#!/system/bin/sh

echo 'Pixel 9 series modem tuning'

# 3GPP R16
echo 'Set 3GPP rel16 for LTE and NR'
echo '
AT+GOOGSETNV="UECAPA_AS_RELEASE",0,"08"\r
AT+GOOGSETNV="UECAPA_AS_RELEASE",1,"08"\r
AT+GOOGSETNV="!NRRRC_INSERT_TEST_AS_RELEASE_VER",0,"01,00,00,00"\r
AT+GOOGSETNV="!NRRRC_INSERT_TEST_AS_RELEASE_VER_DS",0,"01,00,00,00"\r
' > /dev/umts_router & cat /dev/umts_router

# LTE Tuning

echo 'LTE feature tuning'
echo 'Max category, 256QAL UL, Alt TBS index, Beamforming ref signal, TX ant selection, VoLTE recommended bitrate'
echo '
AT+GOOGSETNV="UECAPA_UE_CATEGORY",0,"0C"\r
AT+GOOGSETNV="UECAPA_UE_CATEGORY",1,"0C"\r
AT+GOOGSETNV="UECAPA_REL12_CATEGORY_DL",0,"14"\r
AT+GOOGSETNV="UECAPA_REL12_CATEGORY_DL",1,"14"\r
AT+GOOGSETNV="UECAPA_REL12_CATEGORY_UL",0,"12"\r
AT+GOOGSETNV="UECAPA_REL12_CATEGORY_UL",1,"12"\r
AT+GOOGSETNV="UECAPA_REL14_UL_256QAM_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL14_UL_256QAM_SUPPORT",1,"01"\r
AT+GOOGSETNV="UECAPA_REL15_FSULPCC_1_256Q",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_FSULPCC_2_256Q",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_FSULPCC_1_256Q_DS",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_FSULPCC_2_256Q_DS",0,"01"\r
AT+GOOGSETNV="UECAPA_REL14_ALTERNATIVE_TBS_INDEX_R14_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL14_ALTERNATIVE_TBS_INDEX_R14_SUPPORT",1,"01"\r
AT+GOOGSETNV="UECAPA_REL12_ALTERNATIVE_TBS_INDICES_R12_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_ALTERNATIVE_TBS_INDICES_R12_SUPPORT",1,"01"\r
AT+GOOGSETNV="UECAPA_REL14_RECOMM_BIT_RATE",0,"01"\r
AT+GOOGSETNV="UECAPA_REL14_RECOMM_BIT_RATE",1,"01"\r
AT+GOOGSETNV="UECAPA_REL14_RECOMM_BIT_RATE_QUERY",0,"01"\r
AT+GOOGSETNV="UECAPA_REL14_RECOMM_BIT_RATE_QUERY",1,"01"\r
AT+GOOGSETNV="UECAPA_PHY_UE_SPECIFIC_REF_SIG_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_PHY_UE_SPECIFIC_REF_SIG_SUPPORT",1,"01"\r
AT+GOOGSETNV="UECAPA_PHY_UE_TX_ANTENNASEL_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_PHY_UE_TX_ANTENNASEL_SUPPORT",1,"01"\r
' > /dev/umts_router & cat /dev/umts_router

# NR capability tuning

# NR FR1/FR2 (without roaming)
echo 'Enable NR FR1/FR2 and NR 256QAM capability tuning (domestic only)'
echo '
AT+GOOGSETNV="OEM_GFEATURE_PIXEL_MMW_DISABLE_NEED_TO_DISABLE",0,"00"\r
AT+GOOGSETNV="OEM_GFEATURE_PIXEL_MMW_DISABLE_NEED_TO_DISABLE_DS",0,"00"\r
AT+GOOGSETNV="OEM_GFEATURE_MMW_DISABLE_PER_CARRIER_SKU",0,"00"\r
AT+GOOGSETNV="OEM_GFEATURE_MMW_DISABLE_PER_CARRIER_SKU_DS",0,"00"\r
AT+GOOGSETNV="OEM_GFEATURE_PIXEL_MMW_DISABLE_CARRIER_ID_MODE",0,"00"\r
AT+GOOGSETNV="!NRRRC.SIM_BASED_BAND_LIST_SUPPORT",0,"00"\r
AT+GOOGSETNV="!NRRRC.SIM_OPERATOR_BAND_LIST",0,"00,00"\r
AT+GOOGSETNV="NR.CONFIG.MODE",0,"11"\r
AT+GOOGSETNV="DS.NR.CONFIG.MODE",0,"11"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_FR1_BM",0,"0A,C8"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_FR1_BM_DS",0,"0A,C8"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_FR2_BM",0,"DC,C5"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_FR2_BM_DS",0,"DC,C5"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_21_FBI",0,"11,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_22_FBI",0,"12,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_23_FBI",0,"13,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_24_FBI",0,"14,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_21_FBI_DS",0,"11,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_22_FBI_DS",0,"12,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_23_FBI_DS",0,"13,28"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_24_FBI_DS",0,"14,28"\r
AT+GOOGSETNV="NRRRC.SIM_BASED_BAND_LIST_SUPPORT",0,"00"\r
' > /dev/umts_router & cat /dev/umts_router


# NR capability DSS, SRS TX switch, NSA dynamic power sharing, BWP
echo 'Enable NR SRS TX switch, DSS, NSA dynamic power sharing, BWP, RRC Inactive, RRC Segment, AGAP, WUS, CHO, UAI, High-speed enhancement, Tx Diversity'
echo '
AT+GOOGSETNV="!NRCAPA.Gen.SrsTxSwitch",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Switch.DssFeature",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Switch.DssFeature_DS",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Gen.DynamicPowerSharing",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Gen.DynamicPowerSharing_DS",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Band.BwpSameNumerology",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Band.BwpSameNumerology_DS",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Band.BwpDiffNumerology",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Band.BwpDiffNumerology_DS",0,"01"\r
AT+GOOGSETNV="!NRCAPA_INACTIVE_STATE",0,"01"\r
AT+GOOGSETNV="!NRCAPA_INACTIVE_STATE_DS",0,"01"\r
AT+GOOGSETNV="UECAPA_REL16_UL_RRC_SEGMENTATION_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL16_UL_RRC_SEGMENTATION_SUPPORT",1,"01"\r
AT+GOOGSETNV="!NRRRC_R16_UL_RRC_SEGMENTATION",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_UL_RRC_SEGMENTATION_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_AGAP_EUTRA_SUPPORT",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_AGAP_EUTRA_SUPPORT_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_AGAP_SUPPORT",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_AGAP_SUPPORT_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_WUS_SUPPORT",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_WUS_SUPPORT_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_UAI_SUPPORT",0,"01"\r
AT+GOOGSETNV="!NRRRC.R16_UAI_SUPPORT_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_CHO_SUPPORT",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_CHO_SUPPORT_DS",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_HIGH_SPEED_TRAIN",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_TX_DIVERSITY",0,"01"\r
AT+GOOGSETNV="!NRRRC_R16_TX_DIVERSITY_DS",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router

# HPUE
echo 'Enable LTE B38/41 HPUE, NR n38/40/41/77/78 PC2 and n41/77/78 PC1.5'
echo '
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS",0,"29,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS",1,"4D,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS",2,"4E,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS_NUM",0,"03"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS_DS",0,"29,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS_DS",1,"4D,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS_DS",2,"4E,00"\r
AT+GOOGSETNV="!NRCOMM_PC1DOT5_SUPPORTED_BANDS_NUM_DS",0,"03"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS_NUM",0,"05"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS",0,"26,00"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS",1,"28,00"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS",2,"29,00"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS",3,"4D,00"\r
AT+GOOGSETNV="!NRCOMM_HPUE_SUPPORTED_BANDS",4,"4E,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_SUPPORTED",0,"01"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_SUPPORTED_DS",0,"01"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS",0,"26,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS",1,"28,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS",2,"29,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS",3,"4D,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS",4,"4E,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS_DS",0,"26,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS_DS",1,"28,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS_DS",2,"29,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS_DS",3,"4D,00"\r
AT+GOOGSETNV="!NRCAPA_NSA_HPUE_BANDS_DS",4,"4E,00"\r
AT+GOOGSETNV="!LTE.COMMON.HPUE.SUPPORTED_BANDS",0,"26"\r
AT+GOOGSETNV="!LTE.COMMON.HPUE.SUPPORTED_BANDS",1,"29"\r
AT+GOOGSETNV="!LTE.COMMON.HPUE.SUPPORTED_BANDS_NUM",0,"02,00"\r
' > /dev/umts_router & cat /dev/umts_router

# NR-DC
echo 'Enable NR-DC'
echo '
AT+GOOGSETNV="!NRCOMMON.NrDcSupport",0,"01"\r
AT+GOOGSETNV="!NRCOMMON.NrDcSupport_DS",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router


# NR n1 45MHz capability
echo 'Enable n1 45MHz'
echo '
AT+GOOGSETNV="UECAPA_NR_RF_BAND_1_CHDL_V1590_SCS15",0,"00,40"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_1_CHUL_V1590_SCS15",0,"00,40"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_1_CHDL_V1590_SCS15_DS",0,"00,40"\r
AT+GOOGSETNV="UECAPA_NR_RF_BAND_1_CHUL_V1590_SCS15_DS",0,"00,40"\r
' > /dev/umts_router & cat /dev/umts_router
